// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOQvjla3pCxZZSkeem8EWIfm_2GEERJEU',
    appId: '1:523373257310:web:134c22718b7581cbb84acf',
    messagingSenderId: '523373257310',
    projectId: 'rmsdelivery-54555',
    authDomain: 'rmsdelivery-54555.firebaseapp.com',
    storageBucket: 'rmsdelivery-54555.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVo0yFfFFNL5oqpztUr1odhKZ6nFRbUxE',
    appId: '1:523373257310:android:b1bbecb0085f6dc2b84acf',
    messagingSenderId: '523373257310',
    projectId: 'rmsdelivery-54555',
    storageBucket: 'rmsdelivery-54555.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYejCLSaxWZ2fisrEVHQA_kLyy7sOVnmc',
    appId: '1:523373257310:ios:c67d7bdb8b384924b84acf',
    messagingSenderId: '523373257310',
    projectId: 'rmsdelivery-54555',
    storageBucket: 'rmsdelivery-54555.appspot.com',
    iosClientId: '523373257310-a4974i1uopsjbkquablugmlc1r01uigi.apps.googleusercontent.com',
    iosBundleId: 'com.example.rmsDelivery2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYejCLSaxWZ2fisrEVHQA_kLyy7sOVnmc',
    appId: '1:523373257310:ios:af50f64a3b5538a6b84acf',
    messagingSenderId: '523373257310',
    projectId: 'rmsdelivery-54555',
    storageBucket: 'rmsdelivery-54555.appspot.com',
    iosClientId: '523373257310-8bfdh9ieg5po21c0t6od4s08g7a9rv7l.apps.googleusercontent.com',
    iosBundleId: 'com.example.rmsDelivery2.RunnerTests',
  );
}
